path: /home/aadarsh/test/Object-Detection/outputs/bdd100k_preprocessing/bdd100k-yolo-subset-v1
train: images/train
val: images/val
test: images/test

nc: 8

names:
  0: car
  1: person
  2: truck
  3: bus
  4: motor
  5: bike
  6: traffic light
  7: traffic sign